## Notebook for processing TlF CID bike sharing data 

This is a simple helper notebook which reads in raw data as downloaded from https://cycling.data.tfl.gov.uk/

PLease refer to the report for a description of the data.

In [3]:
# imports 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# path and file names 
may_2025_data_part1 = "data/419JourneyDataExtract01May2025-14May2025.csv"
may_2025_data_part2 = "data/420JourneyDataExtract14May2025-31May2025.csv"

store_adjacency_matrices_file = "output/am_bikes.pkl"

In [ ]:
# Data load and preparation routine.  

# Step 1: load and join separate data sets 

full_bike_df1 = pd.read_csv(may_2025_data_part2)
full_bike_df2 = pd.read_csv(may_2025_data_part1)

full_bike_df = pd.concat([full_bike_df1, full_bike_df2])

n_full = len(full_bike_df)

# Step 2: remove self loops 
bike_df = full_bike_df[
    full_bike_df['Start station number'] != full_bike_df['End station number']
    ][
        ["Start date", "Start station number", "End station number"]
        ]

n_filtered = len(bike_df)


# Step 3: Select and rename columns 
bike_df.columns = ["timestamp", "source", "target"]


# Step 4:  Set day of month as t e [1,..,31]
bike_df["tf"] = pd.to_datetime(bike_df["timestamp"]).dt.day -1 

# Make and store a list of unique nodes with properties 

# Step 5: Generate adjacency matrices per day.  This takes a minute or so.  
node_list = list(set(bike_df["source"].unique().tolist() + bike_df["target"].unique().tolist()))
print(len(node_list))

adjacency_matrices = []
for tf in bike_df["tf"].unique():
    adjacency_matrix = np.zeros((len(node_list), len(node_list)))
    for _, row in bike_df[bike_df["tf"] == tf].iterrows():
        i, j = node_list.index(row["source"]), node_list.index(row["target"])
        adjacency_matrix[i, j] = 1
        adjacency_matrix[j, i] = 1  # ensure symmetry 
    adjacency_matrices.append(adjacency_matrix)

# double check for no self loops 
if any(np.diag(adjacency_matrices[0]) > 0):
    raise ValueError("Self loops in adjacency matrix")


# Step 6:  Summarize some stats for end user 

T = len(adjacency_matrices)
n = adjacency_matrices[0].shape[0]

# Total number of edges remaining 
edges_remaining = np.array([
        am.sum()/2
        for am in adjacency_matrices 
    ])

edges_in_dynamic_network = edges_remaining.sum()
edge_density = edges_remaining / (n*(n-1))
avg_edge_density = edge_density.mean()
min_edge_density = edge_density.min()
max_edge_density = edge_density.max()
avg_node_degree = edges_in_dynamic_network / (T*n)

# summarize for end user 

print("Loaded and processed data")
print("Number of days: ".rjust(40), T)
print("Number of nodes: ".rjust(40), n)
print("Initial number of edges: ".rjust(40), n_full)
print("Number of edges after filtering: ".rjust(40), n_filtered)
print("Number of edges in dynamic network: ".rjust(40), int(edges_in_dynamic_network))
print("Min/Mean/Max edge density: ".rjust(40), round(min_edge_density, 3), "/", round(avg_edge_density, 3), "/", round(max_edge_density, 3))
print("Average node degree: ".rjust(40), round(avg_node_degree, 2))

# Step 7:  Save as pickle file for quick reference 
import pickle
with open(store_adjacency_matrices_file, "wb") as f:
    pickle.dump(adjacency_matrices, f)


# Step 8:  Make a list of latitude/longitude per node, sorted after occurrence in the adjacency matrix (which is sorted after the node list)

unique_nodes = pd.concat([
    full_bike_df[["Start station", "Start station number"]].rename(columns={"Start station": "station_name", "Start station number": "station_id"}),
    full_bike_df[["End station", "End station number"]].rename(columns={"End station": "station_name", "End station number": "station_id"})
]).drop_duplicates(subset=["station_id"])

display(pd.DataFrame({"station_id": node_list}).merge(unique_nodes, on="station_id", how="left").sort_values(by="station_name"))

# load lat lon data 
ll_data = pd.read_csv("data/santander_locs.csv").rename(columns={"name": "station_name"}).drop(columns=["id"])

# replace " - " with ", " 
ll_data["station_name"] = ll_data["station_name"].str.replace(" - ", ", ")
display(ll_data.sort_values("station_name"))

merged_data = unique_nodes.merge(ll_data, on="station_name", how="left")

# # join back in the position/index of the station in the node list 
# merged_data["station_idx"] = None 

# for idx, row in merged_data.iterrows():
#     try:
#         print(row["station_id"])
#         idx = node_list.index(row["station_id"])
#         merged_data.at[idx, "station_idx"] = idx
#     except Exception as e:
#         print(e)
#         pass 

# display(merged_data[merged_data["station_idx"].isna()])

# Let us build a dataframe line by line that will match with the node indices implied in the 
# adjacency matrices.  
node_list_extended = pd.DataFrame({"station_id": [int(i) for i in node_list]})
node_list_extended.reset_index(drop=False, inplace=True)
# find duplicate station_id in merged_data 
merged_data = merged_data.drop_duplicates(subset=["station_id"])
node_list_extended = node_list_extended.merge(merged_data, on="station_id", how="left")

node_list_extended.to_csv("data/node_list_extended.csv", index=False)

803
Loaded and processed data
                        Number of days:  31
                       Number of nodes:  803
               Initial number of edges:  859586
       Number of edges after filtering:  828357
    Number of edges in dynamic network:  569147
             Min/Mean/Max edge density:  0.018 / 0.029 / 0.036
                   Average node degree:  22.86

     station_id                       station_name
515        3429  Abbey Orchard Street, Westminster
597      200111      Abbotsbury Road, Holland Park
120        2698    Aberdeen Place, St. John's Wood
617      200078           Aberfeldy Street, Poplar
706      200231        Abingdon Green, Westminster
..          ...                                ...
752       22169               Wren Street, Holborn
305        1094          Wright's Lane, Kensington
368      300230              Wynne Road, Stockwell
520      200042           York Hall, Bethnal Green
440      300235              York Way, Kings Cross

[803 rows x 2 columns]

                          station_name  longitude   latitude
106  Abbey Orchard Street, Westminster  -0.132102  51.498100
532      Abbotsbury Road, Holland Park  -0.205991  51.501400
381    Aberdeen Place, St. John's Wood  -0.176268  51.524800
528           Aberfeldy Street, Poplar  -0.005659  51.513500
553        Abingdon Green, Westminster  -0.125978  51.497600
..                                 ...        ...        ...
410               Wren Street, Holborn  -0.116279  51.524600
154          Wright's Lane, Kensington  -0.193068  51.500400
793              Wynne Road, Stockwell  -0.112687  51.469217
421           York Hall, Bethnal Green  -0.055894  51.528900
800              York Way, Kings Cross  -0.125442  51.541596

[808 rows x 3 columns]

803
803
803
803
803
Empty DataFrame
Columns: [index, station_id, station_name, longitude, latitude]
Index: []

,index,station_id,station_name,longitude,latitude
0,0,1085444,"Old Quebec Street, Marylebone_OLD",NaN,NaN
1,1,300001,"Sandilands Road, Walham Green",-0.191803,51.473600
2,2,1222,"Goswell Road (City Uni), Finsbury",-0.101026,51.528200
3,3,1223,"Buxton Street 1, Shoreditch",-0.068856,51.521800
4,4,1224,"Vauxhall Street, Vauxhall",-0.116625,51.487000
...,...,...,...,...,...
798,798,1213,"Curlew Street, Shad Thames",-0.074189,51.502300
799,799,3499,"Prince Consort Road, Knightsbridge",-0.176416,51.499800
800,800,1057,"Hardwick Street, Clerkenwell",-0.108068,51.527800
801,801,300232,"Riverlight South, Nine Elms",-0.138213,51.481335
802,802,1058,"Edgware Road Station, Marylebone",-0.169774,51.520000

(803, 803)